sudo: required
dist: trusty

addons:
  apt:
    packages:
    - 'libssl-dev'

install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- "export PATH='~/.cargo/bin:$PATH'"

script:
- cargo build --release